<?php
// © 2026 sun-dive. Business Source License 1.1 — see LICENSE.
//
// ── THE `JF` SET: opcode numbering ───────────────────────────────────────────────────────────────────
// ⚠⚠ GENERATED by tools/gen-ops-jf.py from tools/jfmap.py + tools/forth2012.tsv. NEVER EDIT.
//    The human table is ~/Documents/jetmora-jf-wordmap.md, generated from the SAME map, so the
//    two cannot drift. Conformance vectors pin behaviour, not numbering — they would not catch it.
//
// TWO TIERS (design notes §10.5e–§10.5j):
//   jetForth  one byte  — pushes, runtime primitives, all crypto. CONTROLS the covenant.
//   stdForth  two bytes — the complete Forth 2012 vocabulary, one bank per wordset.
//
// ⚠⚠ ISOLATION IS THE POINT (gaps §10.9). Nothing here may be imported by `SV` or `BT`, and
// nothing from them may be imported here. Only the conformance vectors cross the boundary.
//
// ⛔ ONE WORD, ONE ENCODING. A promoted word has ONLY its single-byte form; the bank slot is
// reserved-illegal, because execution is proved by HASHING THE BYTECODE and two encodings of one
// program would mean two hashes.
declare(strict_types=1);

/** direct push of 0..72 bytes: the opcode IS the length. */
const JF_PUSH_MAX = 0x48;

/** small integers 0..8 then -1, contiguous from here. */
const JF_SMALL0 = 0x49;
const JF_SMALL_NEG1 = 0x52;

/** literal and string forms. */
const JF_LIT = [
  'LIT8'=>0x53, 'LIT16'=>0x54, 'LIT32'=>0x55, 'LIT64'=>0x56, 'LITBIG'=>0x57, 'STR8'=>0x58,
  'STR16'=>0x59, 'STR32'=>0x5a,
];

/** jetForth words: name => single byte. */
const JF_WORD = [
  // stack (21)
  '2>R'=>0x5b, '2DROP'=>0x5c, '2DUP'=>0x5d, '2OVER'=>0x5e, '2R>'=>0x5f, '2R@'=>0x60, '2SWAP'=>0x61,
  '>R'=>0x62, '?DUP'=>0x63, 'DEPTH'=>0x64, 'DROP'=>0x65, 'DUP'=>0x66, 'NIP'=>0x67, 'OVER'=>0x68,
  'PICK'=>0x69, 'R>'=>0x6a, 'R@'=>0x6b, 'ROLL'=>0x6c, 'ROT'=>0x6d, 'SWAP'=>0x6e, 'TUCK'=>0x6f,
  // arithmetic (22)
  '*'=>0x70, '*/'=>0x71, '*/MOD'=>0x72, '+'=>0x73, '-'=>0x74, '/'=>0x75, '/MOD'=>0x76, '1+'=>0x77,
  '1-'=>0x78, '2*'=>0x79, '2/'=>0x7a, 'ABS'=>0x7b, 'FM/MOD'=>0x7c, 'M*'=>0x7d, 'MAX'=>0x7e,
  'MIN'=>0x7f, 'MOD'=>0x80, 'NEGATE'=>0x81, 'S>D'=>0x82, 'SM/REM'=>0x83, 'UM*'=>0x84,
  'UM/MOD'=>0x85,
  // logic (6)
  'AND'=>0x86, 'INVERT'=>0x87, 'LSHIFT'=>0x88, 'OR'=>0x89, 'RSHIFT'=>0x8a, 'XOR'=>0x8b,
  // compare (11)
  '0<'=>0x8c, '0<>'=>0x8d, '0='=>0x8e, '0>'=>0x8f, '<'=>0x90, '<>'=>0x91, '='=>0x92, '>'=>0x93,
  'U<'=>0x94, 'U>'=>0x95, 'WITHIN'=>0x96,
  // constant (3)
  'BL'=>0x97, 'FALSE'=>0x98, 'TRUE'=>0x99,
  // memory (15)
  '!'=>0x9a, '+!'=>0x9b, '2!'=>0x9c, '2@'=>0x9d, '@'=>0x9e, 'ALIGNED'=>0x9f, 'C!'=>0xa0,
  'C@'=>0xa1, 'CELL+'=>0xa2, 'CELLS'=>0xa3, 'CHAR+'=>0xa4, 'CHARS'=>0xa5, 'ERASE'=>0xa6,
  'FILL'=>0xa7, 'MOVE'=>0xa8,
  // loop runtime (6)
  'EXECUTE'=>0xa9, 'EXIT'=>0xaa, 'I'=>0xab, 'J'=>0xac, 'LEAVE'=>0xad, 'UNLOOP'=>0xae,
  // abort (1)
  'ABORT'=>0xaf,
  // branch (8)
  '(+LOOP)'=>0xb0, '(?DO)'=>0xb1, '(DO)'=>0xb2, '(LOOP)'=>0xb3, '0BRANCH'=>0xb4, 'BRANCH'=>0xb5,
  'CALL'=>0xb6, 'RET'=>0xb7,
  // tier boundary (1)
  'INVOKE'=>0xb8,
  // locals runtime (4)
  '(FRAME)'=>0xb9, '(LOCAL!)'=>0xba, '(LOCAL@)'=>0xbb, '(UNFRAME)'=>0xbc,
  // abort runtime (1)
  '(ABORT")'=>0xbd,
  // crypto (9)
  'CHECKMULTISIG'=>0xbe, 'CHECKMULTISIGVERIFY'=>0xbf, 'CHECKSIG'=>0xc0, 'CHECKSIGVERIFY'=>0xc1,
  'HASH160'=>0xc2, 'HASH256'=>0xc3, 'RIPEMD160'=>0xc4, 'SHA1'=>0xc5, 'SHA256'=>0xc6,
  // transaction (13)
  'LOCKTIME'=>0xc7, 'NSEQUENCE'=>0xc8, 'OUTPOINT'=>0xc9, 'OUTPUTS-HASH'=>0xca, 'PREIMAGE'=>0xcb,
  'PREVOUTS-HASH'=>0xcc, 'SCRIPTCODE'=>0xcd, 'SEQUENCES-HASH'=>0xce, 'TXVALUE'=>0xcf,
  'TXVERSION'=>0xd0, 'VER'=>0xd1, 'VERIF'=>0xd2, 'VERNOTIF'=>0xd3,
  // byte strings (9)
  'BIN2NUM'=>0xd4, 'BYTES='=>0xd5, 'CAT'=>0xd6, 'LEFT'=>0xd7, 'NUM2BIN'=>0xd8, 'RIGHT'=>0xd9,
  'SIZE'=>0xda, 'SPLIT'=>0xdb, 'SUBSTR'=>0xdc,
];

/** the declared section order the bytes follow: section => words, alphabetical within. */
const JF_SECTION = [
  'stack' => ['2>R', '2DROP', '2DUP', '2OVER', '2R>', '2R@', '2SWAP', '>R', '?DUP', 'DEPTH', 'DROP', 'DUP', 'NIP', 'OVER', 'PICK', 'R>', 'R@', 'ROLL', 'ROT', 'SWAP', 'TUCK'],
  'arithmetic' => ['*', '*/', '*/MOD', '+', '-', '/', '/MOD', '1+', '1-', '2*', '2/', 'ABS', 'FM/MOD', 'M*', 'MAX', 'MIN', 'MOD', 'NEGATE', 'S>D', 'SM/REM', 'UM*', 'UM/MOD'],
  'logic' => ['AND', 'INVERT', 'LSHIFT', 'OR', 'RSHIFT', 'XOR'],
  'compare' => ['0<', '0<>', '0=', '0>', '<', '<>', '=', '>', 'U<', 'U>', 'WITHIN'],
  'constant' => ['BL', 'FALSE', 'TRUE'],
  'memory' => ['!', '+!', '2!', '2@', '@', 'ALIGNED', 'C!', 'C@', 'CELL+', 'CELLS', 'CHAR+', 'CHARS', 'ERASE', 'FILL', 'MOVE'],
  'loop runtime' => ['EXECUTE', 'EXIT', 'I', 'J', 'LEAVE', 'UNLOOP'],
  'abort' => ['ABORT'],
  'branch' => ['(+LOOP)', '(?DO)', '(DO)', '(LOOP)', '0BRANCH', 'BRANCH', 'CALL', 'RET'],
  'tier boundary' => ['INVOKE'],
  'locals runtime' => ['(FRAME)', '(LOCAL!)', '(LOCAL@)', '(UNFRAME)'],
  'abort runtime' => ['(ABORT")'],
  'crypto' => ['CHECKMULTISIG', 'CHECKMULTISIGVERIFY', 'CHECKSIG', 'CHECKSIGVERIFY', 'HASH160', 'HASH256', 'RIPEMD160', 'SHA1', 'SHA256'],
  'transaction' => ['LOCKTIME', 'NSEQUENCE', 'OUTPOINT', 'OUTPUTS-HASH', 'PREIMAGE', 'PREVOUTS-HASH', 'SCRIPTCODE', 'SEQUENCES-HASH', 'TXVALUE', 'TXVERSION', 'VER', 'VERIF', 'VERNOTIF'],
  'byte strings' => ['BIN2NUM', 'BYTES=', 'CAT', 'LEFT', 'NUM2BIN', 'RIGHT', 'SIZE', 'SPLIT', 'SUBSTR'],
];

/** first escape byte; 0xff is the PLANE escape and is never a wordset. */
const JF_ESC0 = 0xf0;
const JF_PLANE = 0xff;
/** reserved single-byte slots, append-only: 0xdd..0xef (19). */
const JF_RESERVED0 = 0xdd;

/** escape byte => wordset name. An unimplemented bank must be refused BY NAME. */
const JF_BANK = [
  0xf0 => 'CORE',
  0xf1 => 'BLOCK',
  0xf2 => 'DOUBLE',
  0xf3 => 'EXCEPTION',
  0xf4 => 'FACILITY',
  0xf5 => 'FILE',
  0xf6 => 'FLOATING',
  0xf7 => 'LOCAL',
  0xf8 => 'MEMORY',
  0xf9 => 'SEARCH',
  0xfa => 'STRING',
  0xfb => 'TOOLS',
  0xfc => 'XCHAR',
];

/** wordset => words in slot order (base words, then EXT). Alphabetical first fill,
 *  APPEND-ONLY afterwards: a conformance vector pins the encoding, and an insert would
 *  silently renumber everything above it. */
const JF_BANK_WORD = [
  'CORE' => [
    '!'=>0x00, '#'=>0x01, '#>'=>0x02, '#S'=>0x03, '\''=>0x04, '('=>0x05, '*'=>0x06, '*/'=>0x07,
    '*/MOD'=>0x08, '+'=>0x09, '+!'=>0x0a, '+LOOP'=>0x0b, ','=>0x0c, '-'=>0x0d, '.'=>0x0e,
    '."'=>0x0f, '/'=>0x10, '/MOD'=>0x11, '0<'=>0x12, '0='=>0x13, '1+'=>0x14, '1-'=>0x15,
    '2!'=>0x16, '2*'=>0x17, '2/'=>0x18, '2@'=>0x19, '2DROP'=>0x1a, '2DUP'=>0x1b, '2OVER'=>0x1c,
    '2SWAP'=>0x1d, ':'=>0x1e, ';'=>0x1f, '<'=>0x20, '<#'=>0x21, '='=>0x22, '>'=>0x23,
    '>BODY'=>0x24, '>IN'=>0x25, '>NUMBER'=>0x26, '>R'=>0x27, '?DUP'=>0x28, '@'=>0x29,
    'ABORT'=>0x2a, 'ABORT"'=>0x2b, 'ABS'=>0x2c, 'ACCEPT'=>0x2d, 'ALIGN'=>0x2e, 'ALIGNED'=>0x2f,
    'ALLOT'=>0x30, 'AND'=>0x31, 'BASE'=>0x32, 'BEGIN'=>0x33, 'BL'=>0x34, 'C!'=>0x35, 'C,'=>0x36,
    'C@'=>0x37, 'CELL+'=>0x38, 'CELLS'=>0x39, 'CHAR'=>0x3a, 'CHAR+'=>0x3b, 'CHARS'=>0x3c,
    'CONSTANT'=>0x3d, 'COUNT'=>0x3e, 'CR'=>0x3f, 'CREATE'=>0x40, 'DECIMAL'=>0x41, 'DEPTH'=>0x42,
    'DO'=>0x43, 'DOES>'=>0x44, 'DROP'=>0x45, 'DUP'=>0x46, 'ELSE'=>0x47, 'EMIT'=>0x48,
    'ENVIRONMENT?'=>0x49, 'EVALUATE'=>0x4a, 'EXECUTE'=>0x4b, 'EXIT'=>0x4c, 'FILL'=>0x4d,
    'FIND'=>0x4e, 'FM/MOD'=>0x4f, 'HERE'=>0x50, 'HOLD'=>0x51, 'I'=>0x52, 'IF'=>0x53,
    'IMMEDIATE'=>0x54, 'INVERT'=>0x55, 'J'=>0x56, 'KEY'=>0x57, 'LEAVE'=>0x58, 'LITERAL'=>0x59,
    'LOOP'=>0x5a, 'LSHIFT'=>0x5b, 'M*'=>0x5c, 'MAX'=>0x5d, 'MIN'=>0x5e, 'MOD'=>0x5f, 'MOVE'=>0x60,
    'NEGATE'=>0x61, 'OR'=>0x62, 'OVER'=>0x63, 'POSTPONE'=>0x64, 'QUIT'=>0x65, 'R>'=>0x66,
    'R@'=>0x67, 'RECURSE'=>0x68, 'REPEAT'=>0x69, 'ROT'=>0x6a, 'RSHIFT'=>0x6b, 'S"'=>0x6c,
    'S>D'=>0x6d, 'SIGN'=>0x6e, 'SM/REM'=>0x6f, 'SOURCE'=>0x70, 'SPACE'=>0x71, 'SPACES'=>0x72,
    'STATE'=>0x73, 'SWAP'=>0x74, 'THEN'=>0x75, 'TYPE'=>0x76, 'U.'=>0x77, 'U<'=>0x78, 'UM*'=>0x79,
    'UM/MOD'=>0x7a, 'UNLOOP'=>0x7b, 'UNTIL'=>0x7c, 'VARIABLE'=>0x7d, 'WHILE'=>0x7e, 'WORD'=>0x7f,
    'XOR'=>0x80, '['=>0x81, '[\']'=>0x82, '[CHAR]'=>0x83, ']'=>0x84, '.('=>0x85, '.R'=>0x86,
    '0<>'=>0x87, '0>'=>0x88, '2>R'=>0x89, '2R>'=>0x8a, '2R@'=>0x8b, ':NONAME'=>0x8c, '<>'=>0x8d,
    '?DO'=>0x8e, 'ACTION-OF'=>0x8f, 'AGAIN'=>0x90, 'BUFFER:'=>0x91, 'C"'=>0x92, 'CASE'=>0x93,
    'COMPILE,'=>0x94, 'DEFER'=>0x95, 'DEFER!'=>0x96, 'DEFER@'=>0x97, 'ENDCASE'=>0x98,
    'ENDOF'=>0x99, 'ERASE'=>0x9a, 'FALSE'=>0x9b, 'HEX'=>0x9c, 'HOLDS'=>0x9d, 'IS'=>0x9e,
    'MARKER'=>0x9f, 'NIP'=>0xa0, 'OF'=>0xa1, 'PAD'=>0xa2, 'PARSE'=>0xa3, 'PARSE-NAME'=>0xa4,
    'PICK'=>0xa5, 'REFILL'=>0xa6, 'RESTORE-INPUT'=>0xa7, 'ROLL'=>0xa8, 'SAVE-INPUT'=>0xa9,
    'SOURCE-ID'=>0xaa, 'S\\"'=>0xab, 'TO'=>0xac, 'TRUE'=>0xad, 'TUCK'=>0xae, 'U.R'=>0xaf,
    'U>'=>0xb0, 'UNUSED'=>0xb1, 'VALUE'=>0xb2, 'WITHIN'=>0xb3, '[COMPILE]'=>0xb4, '\\'=>0xb5,
  ],
  'BLOCK' => [
    'BLK'=>0x00, 'BLOCK'=>0x01, 'BUFFER'=>0x02, 'FLUSH'=>0x03, 'LOAD'=>0x04, 'SAVE-BUFFERS'=>0x05,
    'UPDATE'=>0x06, 'EMPTY-BUFFERS'=>0x07, 'LIST'=>0x08, 'SCR'=>0x09, 'THRU'=>0x0a,
  ],
  'DOUBLE' => [
    '2CONSTANT'=>0x00, '2LITERAL'=>0x01, '2VARIABLE'=>0x02, 'D+'=>0x03, 'D-'=>0x04, 'D.'=>0x05,
    'D.R'=>0x06, 'D0<'=>0x07, 'D0='=>0x08, 'D2*'=>0x09, 'D2/'=>0x0a, 'D<'=>0x0b, 'D='=>0x0c,
    'D>S'=>0x0d, 'DABS'=>0x0e, 'DMAX'=>0x0f, 'DMIN'=>0x10, 'DNEGATE'=>0x11, 'M*/'=>0x12,
    'M+'=>0x13, '2ROT'=>0x14, '2VALUE'=>0x15, 'DU<'=>0x16,
  ],
  'EXCEPTION' => [
    'CATCH'=>0x00, 'THROW'=>0x01,
  ],
  'FACILITY' => [
    'AT-XY'=>0x00, 'KEY?'=>0x01, 'PAGE'=>0x02, '+FIELD'=>0x03, 'BEGIN-STRUCTURE'=>0x04,
    'CFIELD:'=>0x05, 'EKEY'=>0x06, 'EKEY>CHAR'=>0x07, 'EKEY>FKEY'=>0x08, 'EKEY?'=>0x09,
    'EMIT?'=>0x0a, 'END-STRUCTURE'=>0x0b, 'FIELD:'=>0x0c, 'K-ALT-MASK'=>0x0d, 'K-CTRL-MASK'=>0x0e,
    'K-DELETE'=>0x0f, 'K-DOWN'=>0x10, 'K-END'=>0x11, 'K-F1'=>0x12, 'K-F10'=>0x13, 'K-F11'=>0x14,
    'K-F12'=>0x15, 'K-F2'=>0x16, 'K-F3'=>0x17, 'K-F4'=>0x18, 'K-F5'=>0x19, 'K-F6'=>0x1a,
    'K-F7'=>0x1b, 'K-F8'=>0x1c, 'K-F9'=>0x1d, 'K-HOME'=>0x1e, 'K-INSERT'=>0x1f, 'K-LEFT'=>0x20,
    'K-NEXT'=>0x21, 'K-PRIOR'=>0x22, 'K-RIGHT'=>0x23, 'K-SHIFT-MASK'=>0x24, 'K-UP'=>0x25,
    'MS'=>0x26, 'TIME&DATE'=>0x27,
  ],
  'FILE' => [
    'BIN'=>0x00, 'CLOSE-FILE'=>0x01, 'CREATE-FILE'=>0x02, 'DELETE-FILE'=>0x03,
    'FILE-POSITION'=>0x04, 'FILE-SIZE'=>0x05, 'INCLUDE-FILE'=>0x06, 'INCLUDED'=>0x07,
    'OPEN-FILE'=>0x08, 'R/O'=>0x09, 'R/W'=>0x0a, 'READ-FILE'=>0x0b, 'READ-LINE'=>0x0c,
    'REPOSITION-FILE'=>0x0d, 'RESIZE-FILE'=>0x0e, 'W/O'=>0x0f, 'WRITE-FILE'=>0x10,
    'WRITE-LINE'=>0x11, 'FILE-STATUS'=>0x12, 'FLUSH-FILE'=>0x13, 'INCLUDE'=>0x14,
    'RENAME-FILE'=>0x15, 'REQUIRE'=>0x16, 'REQUIRED'=>0x17,
  ],
  'FLOATING' => [
    '>FLOAT'=>0x00, 'D>F'=>0x01, 'F!'=>0x02, 'F*'=>0x03, 'F+'=>0x04, 'F-'=>0x05, 'F/'=>0x06,
    'F0<'=>0x07, 'F0='=>0x08, 'F<'=>0x09, 'F>D'=>0x0a, 'F@'=>0x0b, 'FALIGN'=>0x0c,
    'FALIGNED'=>0x0d, 'FCONSTANT'=>0x0e, 'FDEPTH'=>0x0f, 'FDROP'=>0x10, 'FDUP'=>0x11,
    'FLITERAL'=>0x12, 'FLOAT+'=>0x13, 'FLOATS'=>0x14, 'FLOOR'=>0x15, 'FMAX'=>0x16, 'FMIN'=>0x17,
    'FNEGATE'=>0x18, 'FOVER'=>0x19, 'FROT'=>0x1a, 'FROUND'=>0x1b, 'FSWAP'=>0x1c, 'FVARIABLE'=>0x1d,
    'REPRESENT'=>0x1e, 'DF!'=>0x1f, 'DF@'=>0x20, 'DFALIGN'=>0x21, 'DFALIGNED'=>0x22,
    'DFFIELD:'=>0x23, 'DFLOAT+'=>0x24, 'DFLOATS'=>0x25, 'F**'=>0x26, 'F.'=>0x27, 'F>S'=>0x28,
    'FABS'=>0x29, 'FACOS'=>0x2a, 'FACOSH'=>0x2b, 'FALOG'=>0x2c, 'FASIN'=>0x2d, 'FASINH'=>0x2e,
    'FATAN'=>0x2f, 'FATAN2'=>0x30, 'FATANH'=>0x31, 'FCOS'=>0x32, 'FCOSH'=>0x33, 'FE.'=>0x34,
    'FEXP'=>0x35, 'FEXPM1'=>0x36, 'FFIELD:'=>0x37, 'FLN'=>0x38, 'FLNP1'=>0x39, 'FLOG'=>0x3a,
    'FS.'=>0x3b, 'FSIN'=>0x3c, 'FSINCOS'=>0x3d, 'FSINH'=>0x3e, 'FSQRT'=>0x3f, 'FTAN'=>0x40,
    'FTANH'=>0x41, 'FTRUNC'=>0x42, 'FVALUE'=>0x43, 'F~'=>0x44, 'PRECISION'=>0x45, 'S>F'=>0x46,
    'SET-PRECISION'=>0x47, 'SF!'=>0x48, 'SF@'=>0x49, 'SFALIGN'=>0x4a, 'SFALIGNED'=>0x4b,
    'SFFIELD:'=>0x4c, 'SFLOAT+'=>0x4d, 'SFLOATS'=>0x4e,
  ],
  'LOCAL' => [
    '(LOCAL)'=>0x00, 'LOCALS|'=>0x01, '{:'=>0x02,
  ],
  'MEMORY' => [
    'ALLOCATE'=>0x00, 'FREE'=>0x01, 'RESIZE'=>0x02,
  ],
  'SEARCH' => [
    'DEFINITIONS'=>0x00, 'FORTH-WORDLIST'=>0x01, 'GET-CURRENT'=>0x02, 'GET-ORDER'=>0x03,
    'SEARCH-WORDLIST'=>0x04, 'SET-CURRENT'=>0x05, 'SET-ORDER'=>0x06, 'WORDLIST'=>0x07,
    'ALSO'=>0x08, 'FORTH'=>0x09, 'ONLY'=>0x0a, 'ORDER'=>0x0b, 'PREVIOUS'=>0x0c,
  ],
  'STRING' => [
    '-TRAILING'=>0x00, '/STRING'=>0x01, 'BLANK'=>0x02, 'CMOVE'=>0x03, 'CMOVE>'=>0x04,
    'COMPARE'=>0x05, 'SEARCH'=>0x06, 'SLITERAL'=>0x07, 'REPLACES'=>0x08, 'SUBSTITUTE'=>0x09,
    'UNESCAPE'=>0x0a,
  ],
  'TOOLS' => [
    '.S'=>0x00, '?'=>0x01, 'DUMP'=>0x02, 'SEE'=>0x03, 'WORDS'=>0x04, ';CODE'=>0x05, 'AHEAD'=>0x06,
    'ASSEMBLER'=>0x07, 'BYE'=>0x08, 'CODE'=>0x09, 'CS-PICK'=>0x0a, 'CS-ROLL'=>0x0b, 'EDITOR'=>0x0c,
    'FORGET'=>0x0d, 'N>R'=>0x0e, 'NAME>COMPILE'=>0x0f, 'NAME>INTERPRET'=>0x10, 'NAME>STRING'=>0x11,
    'NR>'=>0x12, 'SYNONYM'=>0x13, 'TRAVERSE-WORDLIST'=>0x14, '[DEFINED]'=>0x15, '[ELSE]'=>0x16,
    '[IF]'=>0x17, '[THEN]'=>0x18, '[UNDEFINED]'=>0x19,
  ],
  'XCHAR' => [
    'X-SIZE'=>0x00, 'XC!+'=>0x01, 'XC!+?'=>0x02, 'XC,'=>0x03, 'XC-SIZE'=>0x04, 'XC@+'=>0x05,
    'XCHAR+'=>0x06, 'XEMIT'=>0x07, 'XKEY'=>0x08, 'XKEY?'=>0x09, '+X/STRING'=>0x0a,
    '-TRAILING-GARBAGE'=>0x0b, 'EKEY>XCHAR'=>0x0c, 'X-WIDTH'=>0x0d, 'XC-WIDTH'=>0x0e,
    'XCHAR-'=>0x0f, 'XHOLD'=>0x10, 'X\\STRING-'=>0x11,
  ],
];

/** ⚠⚠ MEASURED: of the 98 CORE words left in the bank, ZERO are runtime data operations.
 *  The 84 promoted words ARE the complete runtime CORE. So the CORE bank is an ENCODING
 *  RESERVATION — the numbers exist so the map stays derivable from the standard — and each
 *  word is refused saying WHICH KIND it is, which is a different thing from "not built yet". */
const JF_CORE_KIND = [
  '#' => 'number formatting',
  '#>' => 'number formatting',
  '#S' => 'number formatting',
  '\'' => 'text interpretation',
  '(' => 'compile-time',
  '+LOOP' => 'compile-time',
  ',' => 'compile-time',
  '.' => 'number formatting',
  '."' => 'text interpretation',
  '.(' => 'number formatting',
  '.R' => 'number formatting',
  ':' => 'compile-time',
  ':NONAME' => 'compile-time',
  ';' => 'compile-time',
  '<#' => 'number formatting',
  '>BODY' => 'compile-time',
  '>IN' => 'text interpretation',
  '>NUMBER' => 'text interpretation',
  '?DO' => 'compile-time',
  'ABORT"' => 'compile-time',
  'ACCEPT' => 'input channel',
  'ACTION-OF' => 'compile-time',
  'AGAIN' => 'compile-time',
  'ALIGN' => 'compile-time',
  'ALLOT' => 'compile-time',
  'BASE' => 'number formatting',
  'BEGIN' => 'compile-time',
  'BUFFER:' => 'compile-time',
  'C"' => 'text interpretation',
  'C,' => 'compile-time',
  'CASE' => 'compile-time',
  'CHAR' => 'text interpretation',
  'COMPILE,' => 'compile-time',
  'CONSTANT' => 'compile-time',
  'COUNT' => 'text interpretation',
  'CR' => 'output channel',
  'CREATE' => 'compile-time',
  'DECIMAL' => 'number formatting',
  'DEFER' => 'compile-time',
  'DEFER!' => 'compile-time',
  'DEFER@' => 'compile-time',
  'DO' => 'compile-time',
  'DOES>' => 'compile-time',
  'ELSE' => 'compile-time',
  'EMIT' => 'output channel',
  'ENDCASE' => 'compile-time',
  'ENDOF' => 'compile-time',
  'ENVIRONMENT?' => 'system',
  'EVALUATE' => 'runtime text interpretation — this is OP_EVAL',
  'FIND' => 'text interpretation',
  'HERE' => 'compile-time',
  'HEX' => 'number formatting',
  'HOLD' => 'number formatting',
  'HOLDS' => 'number formatting',
  'IF' => 'compile-time',
  'IMMEDIATE' => 'compile-time',
  'IS' => 'compile-time',
  'KEY' => 'input channel',
  'LITERAL' => 'compile-time',
  'LOOP' => 'compile-time',
  'MARKER' => 'compile-time',
  'OF' => 'compile-time',
  'PAD' => 'compile-time',
  'PARSE' => 'text interpretation',
  'PARSE-NAME' => 'text interpretation',
  'POSTPONE' => 'compile-time',
  'QUIT' => 'system',
  'RECURSE' => 'compile-time',
  'REFILL' => 'text interpretation',
  'REPEAT' => 'compile-time',
  'RESTORE-INPUT' => 'text interpretation',
  'S"' => 'text interpretation',
  'SAVE-INPUT' => 'text interpretation',
  'SIGN' => 'number formatting',
  'SOURCE' => 'text interpretation',
  'SOURCE-ID' => 'text interpretation',
  'SPACE' => 'output channel',
  'SPACES' => 'output channel',
  'STATE' => 'system',
  'S\\"' => 'text interpretation',
  'THEN' => 'compile-time',
  'TO' => 'compile-time',
  'TYPE' => 'output channel',
  'U.' => 'number formatting',
  'U.R' => 'number formatting',
  'UNTIL' => 'compile-time',
  'UNUSED' => 'compile-time',
  'VALUE' => 'compile-time',
  'VARIABLE' => 'compile-time',
  'WHILE' => 'compile-time',
  'WORD' => 'text interpretation',
  '[' => 'compile-time',
  '[\']' => 'compile-time',
  '[CHAR]' => 'compile-time',
  '[COMPILE]' => 'compile-time',
  '\\' => 'compile-time',
  ']' => 'compile-time',
];

/** words promoted to jetForth: their two-byte form MUST be refused. */
const JF_PROMOTED = [
  '!'=>0x9a, '*'=>0x70, '*/'=>0x71, '*/MOD'=>0x72, '+'=>0x73, '+!'=>0x9b, '-'=>0x74, '/'=>0x75,
  '/MOD'=>0x76, '0<'=>0x8c, '0<>'=>0x8d, '0='=>0x8e, '0>'=>0x8f, '1+'=>0x77, '1-'=>0x78,
  '2!'=>0x9c, '2*'=>0x79, '2/'=>0x7a, '2>R'=>0x5b, '2@'=>0x9d, '2DROP'=>0x5c, '2DUP'=>0x5d,
  '2OVER'=>0x5e, '2R>'=>0x5f, '2R@'=>0x60, '2SWAP'=>0x61, '<'=>0x90, '<>'=>0x91, '='=>0x92,
  '>'=>0x93, '>R'=>0x62, '?DUP'=>0x63, '@'=>0x9e, 'ABORT'=>0xaf, 'ABS'=>0x7b, 'ALIGNED'=>0x9f,
  'AND'=>0x86, 'BL'=>0x97, 'C!'=>0xa0, 'C@'=>0xa1, 'CELL+'=>0xa2, 'CELLS'=>0xa3, 'CHAR+'=>0xa4,
  'CHARS'=>0xa5, 'DEPTH'=>0x64, 'DROP'=>0x65, 'DUP'=>0x66, 'ERASE'=>0xa6, 'EXECUTE'=>0xa9,
  'EXIT'=>0xaa, 'FALSE'=>0x98, 'FILL'=>0xa7, 'FM/MOD'=>0x7c, 'I'=>0xab, 'INVERT'=>0x87, 'J'=>0xac,
  'LEAVE'=>0xad, 'LSHIFT'=>0x88, 'M*'=>0x7d, 'MAX'=>0x7e, 'MIN'=>0x7f, 'MOD'=>0x80, 'MOVE'=>0xa8,
  'NEGATE'=>0x81, 'NIP'=>0x67, 'OR'=>0x89, 'OVER'=>0x68, 'PICK'=>0x69, 'R>'=>0x6a, 'R@'=>0x6b,
  'ROLL'=>0x6c, 'ROT'=>0x6d, 'RSHIFT'=>0x8a, 'S>D'=>0x82, 'SM/REM'=>0x83, 'SWAP'=>0x6e,
  'TRUE'=>0x99, 'TUCK'=>0x6f, 'U<'=>0x94, 'U>'=>0x95, 'UM*'=>0x84, 'UM/MOD'=>0x85, 'UNLOOP'=>0xae,
  'WITHIN'=>0x96, 'XOR'=>0x8b,
];

/** single byte => name, for errors and for `SEE`-style rendering. */
function jf_op_name(int $n): string {
  static $rev = null;
  if ($rev === null) {
    $rev = [];
    foreach (JF_WORD as $k => $v) $rev[$v] = $k;
    foreach (JF_LIT  as $k => $v) $rev[$v] = $k;
    for ($i = 0; $i <= 8; $i++) $rev[JF_SMALL0 + $i] = (string)$i;
    $rev[JF_SMALL_NEG1] = '-1';
  }
  if ($n <= JF_PUSH_MAX) return sprintf('PUSH%d', $n);
  if ($n >= JF_ESC0)     return sprintf('BANK:%s', JF_BANK[$n] ?? '?');
  return $rev[$n] ?? sprintf('JF_UNKNOWN_%02x', $n);
}

/** bank escape => wordset, or null when the byte is not an escape. */
function jf_bank_name(int $esc): ?string { return JF_BANK[$esc] ?? null; }

// generated 2026-09-15
