#!/usr/bin/env python3
"""Emit server/ops-jf.php from tools/jfmap.py. ⚠ Never edit the .php — edit the map."""
import os, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import jfmap

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'server', 'ops-jf.php')


def q(s):
    """PHP single-quoted string literal."""
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def table(pairs, indent='  ', width=100):
    """name => code, wrapped."""
    out, line = [], indent
    for k, v in pairs:
        piece = f'{q(k)}=>0x{v:02x}, '
        if len(line) + len(piece) > width:
            out.append(line.rstrip()); line = indent
        line += piece
    if line.strip():
        out.append(line.rstrip())
    return '\n'.join(out)


def main():
    m = jfmap.assign()
    code, banks = m['code'], m['banks']
    L = []
    A = L.append
    A('<?php')
    A('// © 2026 sun-dive. Business Source License 1.1 — see LICENSE.')
    A('//')
    A('// ── THE `JF` SET: opcode numbering ───────────────────────────────────────────────────────────────────')
    A('// ⚠⚠ GENERATED by tools/gen-ops-jf.py from tools/jfmap.py + tools/forth2012.tsv. NEVER EDIT.')
    A('//    The human table is ~/Documents/jetmora-jf-wordmap.md, generated from the SAME map, so the')
    A('//    two cannot drift. Conformance vectors pin behaviour, not numbering — they would not catch it.')
    A('//')
    A('// TWO TIERS (design notes §10.5e–§10.5j):')
    A('//   jetForth  one byte  — pushes, runtime primitives, all crypto. CONTROLS the covenant.')
    A('//   stdForth  two bytes — the complete Forth 2012 vocabulary, one bank per wordset.')
    A('//')
    A('// ⚠⚠ ISOLATION IS THE POINT (gaps §10.9). Nothing here may be imported by `SV` or `BT`, and')
    A('// nothing from them may be imported here. Only the conformance vectors cross the boundary.')
    A('//')
    A('// ⛔ ONE WORD, ONE ENCODING. A promoted word has ONLY its single-byte form; the bank slot is')
    A('// reserved-illegal, because execution is proved by HASHING THE BYTECODE and two encodings of one')
    A('// program would mean two hashes.')
    A('declare(strict_types=1);')
    A('')
    A(f'/** direct push of 0..{m["n_push"]-1} bytes: the opcode IS the length. */')
    A(f'const JF_PUSH_MAX = 0x{m["n_push"]-1:02x};')
    A('')
    A(f'/** small integers 0..{max(i for i in jfmap.SMALL_INTS)} then -1, contiguous from here. */')
    A(f'const JF_SMALL0 = 0x{code["#0"]:02x};')
    A(f'const JF_SMALL_NEG1 = 0x{code["#-1"]:02x};')
    A('')
    A('/** literal and string forms. */')
    A('const JF_LIT = [')
    A(table([(w, code[w]) for w, _ in jfmap.LITFORMS]))
    A('];')
    A('')
    A('/** jetForth words: name => single byte. */')
    A('const JF_WORD = [')
    # ★ Emitted in byte order: the sections ARE the numbering (sections by category, alphabetical within).
    for name, ws in m['sections']:
        A(f'  // {name} ({len(ws)})')
        A(table([(w, code[w]) for w in ws]))
    A('];')
    A('')
    A('/** the declared section order the bytes follow: section => words, alphabetical within. */')
    A('const JF_SECTION = [')
    for name, ws in m['sections']:
        A(f'  {q(name)} => [' + ', '.join(q(w) for w in ws) + '],')
    A('];')
    A('')
    A(f'/** first escape byte; 0x{m["plane"]:02x} is the PLANE escape and is never a wordset. */')
    A(f'const JF_ESC0 = 0x{m["esc0"]:02x};')
    A(f'const JF_PLANE = 0x{m["plane"]:02x};')
    A(f'/** reserved single-byte slots, append-only: 0x{m["resv_at"]:02x}..0x{m["esc0"]-1:02x} ({m["reserve"]}). */')
    A(f'const JF_RESERVED0 = 0x{m["resv_at"]:02x};')
    A('')
    A('/** escape byte => wordset name. An unimplemented bank must be refused BY NAME. */')
    A('const JF_BANK = [')
    A(table([(w, e) for e, (w, _) in sorted(banks.items())][:0]) or
      '\n'.join(f'  0x{e:02x} => {q(w)},' for e, (w, _) in sorted(banks.items())))
    A('];')
    A('')
    A('/** wordset => words in slot order (base words, then EXT). Alphabetical first fill,')
    A(' *  APPEND-ONLY afterwards: a conformance vector pins the encoding, and an insert would')
    A(' *  silently renumber everything above it. */')
    A('const JF_BANK_WORD = [')
    for e, (w, ws) in sorted(banks.items()):
        A(f'  {q(w)} => [')
        A(table([(n, i) for i, n in enumerate(ws)], indent='    '))
        A('  ],')
    A('];')
    A('')
    A('/** ⚠⚠ MEASURED: of the 98 CORE words left in the bank, ZERO are runtime data operations.')
    A(' *  The 84 promoted words ARE the complete runtime CORE. So the CORE bank is an ENCODING')
    A(' *  RESERVATION — the numbers exist so the map stays derivable from the standard — and each')
    A(' *  word is refused saying WHICH KIND it is, which is a different thing from "not built yet". */')
    A('const JF_CORE_KIND = [')
    A(table([(w, 0) for w in []]) or
      '\n'.join(f'  {q(w)} => {q(k)},' for w, k in sorted(jfmap.CORE_KIND.items())))
    A('];')
    A('')
    A('/** words promoted to jetForth: their two-byte form MUST be refused. */')
    A('const JF_PROMOTED = [')
    A(table([(n, code[n]) for n in sorted(m['promoted'])]))
    A('];')
    A('')
    A('/** single byte => name, for errors and for `SEE`-style rendering. */')
    A('function jf_op_name(int $n): string {')
    A('  static $rev = null;')
    A('  if ($rev === null) {')
    A('    $rev = [];')
    A('    foreach (JF_WORD as $k => $v) $rev[$v] = $k;')
    A('    foreach (JF_LIT  as $k => $v) $rev[$v] = $k;')
    A(f'    for ($i = 0; $i <= {max(i for i in jfmap.SMALL_INTS)}; $i++) '
      '$rev[JF_SMALL0 + $i] = (string)$i;')
    A('    $rev[JF_SMALL_NEG1] = \'-1\';')
    A('  }')
    A('  if ($n <= JF_PUSH_MAX) return sprintf(\'PUSH%d\', $n);')
    A('  if ($n >= JF_ESC0)     return sprintf(\'BANK:%s\', JF_BANK[$n] ?? \'?\');')
    A('  return $rev[$n] ?? sprintf(\'JF_UNKNOWN_%02x\', $n);')
    A('}')
    A('')
    A('/** bank escape => wordset, or null when the byte is not an escape. */')
    A('function jf_bank_name(int $esc): ?string { return JF_BANK[$esc] ?? null; }')
    A('')
    A(f'// generated {datetime.date.today().isoformat()}')

    open(OUT, 'w').write('\n'.join(L) + '\n')
    print(f'  ✅ {os.path.normpath(OUT)}')
    print(f'  {len(m["words"])} jetForth words · {len(m["allnames"])} stdForth words in '
          f'{len(banks)} banks · {m["reserve"]} reserved')


if __name__ == '__main__':
    main()
